app = "vc-scraper"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_concurrent_requests = 100

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = [{ port = 80, handlers = ["http"] }, { port = 443, handlers = ["tls", "http"] }]
  auto_stop_machines = true
  auto_start_machines = true

[metrics]
  enabled = true
  port = 9090

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/health"
    timeout = "5s"
    headers = {}

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[restart]
  policy = "on-failure"
  max_retries = 3
